version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - 'postgres_data:/var/lib/postgresql/data:rw'
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
    container_name: "PostgreSQL"

  backend:
    # image: prashw23/backend:latest
    image: backend/ .
    environment:
      DB_HOST: postgreSQL
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: postgres_password
    ports:
      - '8080:8080'
    container_name: "Backend"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    # image: prashw23/frontend:latest  
    image : frontend/ .
    ports:
      - '3000:3000'
    container_name: "Frontend"

volumes:
  postgres_data:
