version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      DB_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - 'postgres_data:/var/lib/postgresql@14/data:rw'
    network_mode: "host"
    container_name: PostgreSQL
    healthcheck:
      test: ['CMD-SHEL' , 'pg_isready -U postgres']
      timeout: 5s
      retries: 5
      start_period: 20s
  backend:
    build: .
    environment:
      DB_HOST: postgreSQL
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: postgres_password
    network_mode: "host"
    container_name: Backend
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    build: ../frontend
    network_mode: "host"
    container_name: Frontend
volumes:
  postgres_data: null
