FROM golang:1.19 

ENV DB_HOST=my-postgres
ENV DB_PORT=5432
ENV DB_USER=postgres
ENV DB_PASSWORD=admin
ENV DB_NAME=postgres

WORKDIR /app/backend
COPY go.mod go.sum ./
# CMD go run main.go 
RUN go mod download && go mod verify
COPY . .
RUN go build -o main .
EXPOSE 8080

CMD ["./main"]
